const translations = {
  pt: {
    title: "Adega Imperial — As Melhores Bebidas Geladas",
    navHome: "Início",
    navCategories: "Bebidas",
    navContact: "Contato",
    orderNow: "Fale Conosco",
    whatsappBtn: "Consultar no WhatsApp",
    openNow: "Aberto agora · Venha nos visitar",
    heroTitle: "Bebidas <span class='text-amber-500 font-display'>estupidamente</span> geladas.",
    heroSubtitle: "Confira nossa seleção exclusiva de cervejas e destilados selecionados. Consulte a disponibilidade pelo WhatsApp.",
    viewDrinks: "Ver bebidas",
    statsOrders: "Bebidas Cadastradas",
    statsTime: "Temperatura Ideal",
    statsRating: "Procedência Garantida",
    highlightsTitle: "Conheça a Adega Imperial",
    highlights: [
      { title: "Sempre Geladas", desc: "Bebidas na temperatura ideal para consumo imediato." },
      { title: "Variedade Selecionada", desc: "Os melhores rótulos e marcas do mercado." },
      { title: "Fácil de Consultar", desc: "Veja o catálogo online e tire suas dúvidas." },
      { title: "Atendimento no WhatsApp", desc: "Consulte disponibilidade de forma rápida." }
    ],
    categoriesTitle: "Categorias",
    categoriesSubtitle: "Escolha sua bebida",
    viewAll: "Ver todas",
    featuredTitle: "Destaques",
    featuredSubtitle: "Mais pedidos",
    viewPromos: "Ver todas",
    ctaTitle: "Veja nosso catálogo de bebidas.",
    ctaSubtitle: "Consulte os preços e tire suas dúvidas diretamente conosco no WhatsApp.",
    ctaBtn: "Consultar no WhatsApp",
    footerDesc: "Adega Imperial. As melhores cervejas e destilados gelados.",
    footerNav: "Navegar",
    footerDelivery: "Informações",
    footerPayment: "Pagamento",
    footerWarning: "Venda e consumo proibidos para menores de 18 anos.",
    footerCopyright: "Adega Imperial. Todos os direitos reservados.",
    // Contact page
    contactTitle: "Fala com a gente",
    contactSubtitle: "O jeito mais rápido de falar conosco é pelo WhatsApp ou Instagram. Consulte a disponibilidade de bebidas.",
    infoPhone: "Telefone / WhatsApp",
    infoHours: "Horário",
    infoHoursVal: "Seg–Dom · 10h às 02h",
    infoAddress: "Endereço",
    infoAddressVal: "R. Manoel Ribeiro, 378, Brasiléia - AC, 69932-000",
    infoDelivery: "Disponibilidade",
    infoDeliveryVal: "Pronta entrega / Retirada",
    paymentMethods: "Formas de pagamento aceitas",
    paymentMethodsList: ["PIX", "Cartão de Crédito", "Cartão de Débito", "Dinheiro"],
    // Product details
    productVolume: "Volume",
    productPack: "Embalagem",
    productServed: "Servido",
    productServedVal: "Estupidamente gelado",
    productDelivery: "Disponibilidade",
    productDeliveryVal: "Em Estoque",
    productPaymentInfo: "Formas de pagamento aceitas: PIX, cartão ou dinheiro.",
    relatedProducts: "Você também pode gostar",
    noProducts: "Nenhuma bebida cadastrada nesta categoria.",
    productNotFound: "Bebida não encontrada",
    categoryNotFound: "Categoria não encontrada",
    backToCategories: "Ver todas",
    addToCart: "Consultar no WhatsApp",
    promoBadge: "Destaque",
    // Catalog Data
    categoriesData: [
      { slug: "cervejas", name: "Cervejas", tagline: "Estupidamente geladas", emoji: "🍺", accent: "from-amber-500/20 to-amber-600/5", image: "../fotos/cerveja.ff.jpeg" },
      { slug: "destilados", name: "Destilados", tagline: "Vodka, whisky, cachaça", emoji: "🥃", accent: "from-yellow-600/20 to-yellow-700/5", image: "../fotos/destilado.fgh.jpg" }
    ],
    productsData: [
      { id: "heineken", name: "Cerveja Heineken", category: "cervejas", size: "Lata 350ml", volume: "350ml", pack: "Fardo c/ 12", description: "Puro malte importado, com sabor refrescante, lúpulo selecionado e espuma cremosa inconfundível. Servida trincando de gelada.", image: "../fotos/Heinekencaixa2.webp", gallery: ["../fotos/Heinekencaixa2.webp", "../fotos/caixa de cervejaheinek.jpg"], emoji: "🍺" },
      { id: "amstel", name: "Cerveja Amstel", category: "cervejas", size: "Lata 350ml", volume: "350ml", pack: "Fardo c/ 12", description: "A tradicional receita europeia puro malte de Amsterdã. Leve, refrescante e perfeita para qualquer momento.", image: "../fotos/caixacervejaamstel.webp", gallery: ["../fotos/caixacervejaamstel.webp", "../fotos/caixadecervejaamstel2.jpg"], emoji: "🍺" },
      { id: "brahma", name: "Cerveja Brahma", category: "cervejas", size: "Lata 350ml", volume: "350ml", pack: "Fardo c/ 12", description: "O sabor do chopp na lata. Espuma cremosa, refrescância clássica e o sabor preferido do churrasco brasileiro.", image: "../fotos/cervejacaixabrahma.webp", gallery: ["../fotos/cervejacaixabrahma.webp", "../fotos/caixadeccervejabrahma2.jpg"], emoji: "🍺" },
      { id: "skol", name: "Cerveja Skol", category: "cervejas", size: "Lata 350ml", volume: "350ml", pack: "Fardo c/ 12", description: "A cerveja que desce redondo. Leveza sem igual, teor alcoólico equilibrado e a queridinha dos encontros.", image: "../fotos/skolcaixa.jpg", gallery: ["../fotos/skolcaixa.jpg", "../fotos/skolcaixa2.jpg"], emoji: "🍺" },
      { id: "campari", name: "Bitter Campari", category: "destilados", size: "Garrafa 900ml", volume: "900ml", pack: "Unidade", description: "O aperitivo clássico italiano. De cor vermelha icônica e sabor amargo inconfundível, ideal para Negroni e Campari Tonic.", image: "../fotos/campare3.webp", gallery: ["../fotos/campare3.webp", "../fotos/campare.png", "../fotos/campare2.jpg", "../fotos/campare4.webp", "../fotos/campare5.webp"], emoji: "🥃" },
      { id: "antarctica", name: "Cerveja Antarctica", category: "cervejas", size: "Lata 350ml", volume: "350ml", pack: "Fardo c/ 12", description: "Cerveja Antarctica Pilsen, uma das mais clássicas do país. Sabor suave, aroma leve e excelente refrescância.", image: "../fotos/antartica.webp", gallery: ["../fotos/antartica.webp", "../fotos/antartica2.jpg", "../fotos/antartica3.jpg", "../fotos/antartica4.jpg"], emoji: "🍺" },
      { id: "itaipava", name: "Cerveja Itaipava", category: "cervejas", size: "Lata 350ml", volume: "350ml", pack: "Fardo c/ 12", description: "Cerveja Itaipava Pilsen. Clara, leve, saborosa e refrescante, ideal para comemorações e dias de calor.", image: "../fotos/itaipava.webp", gallery: ["../fotos/itaipava.webp", "../fotos/itaipava2.webp", "../fotos/itaipava3.webp"], emoji: "🍺" },
      { id: "51", name: "Cachaça 51", category: "destilados", size: "Garrafa 965ml", volume: "965ml", pack: "Unidade", description: "A cachaça mais querida e vendida do Brasil, base indispensável da caipirinha perfeita.", image: "../fotos/caçhaca51.webp", gallery: ["../fotos/caçhaca51.webp", "../fotos/caçhaca51.2.webp"], emoji: "🥃" }
    ]
  }
};
